import logging
from odoo import models, fields, api, _
from odoo.exceptions import UserError

_logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# GraphQL
# ---------------------------------------------------------------------------

QUERY_COLLECTIONS = '''
    query GetCollections($first: Int!, $after: String) {
        collections(first: $first, after: $after) {
            pageInfo { hasNextPage endCursor }
            edges {
                node {
                    id
                    title
                    handle
                    descriptionHtml
                    updatedAt
                    productsCount { count }
                    image { url altText }
                    ruleSet {
                        appliedDisjunctively
                        rules { column relation condition }
                    }
                }
            }
        }
    }
'''

MUTATION_COLLECTION_CREATE = '''
    mutation collectionCreate($input: CollectionInput!) {
        collectionCreate(input: $input) {
            collection { id title handle }
            userErrors { field message }
        }
    }
'''

MUTATION_COLLECTION_UPDATE = '''
    mutation collectionUpdate($input: CollectionInput!) {
        collectionUpdate(input: $input) {
            collection { id title handle }
            userErrors { field message }
        }
    }
'''

MUTATION_COLLECTION_DELETE = '''
    mutation collectionDelete($input: CollectionDeleteInput!) {
        collectionDelete(input: $input) {
            deletedCollectionId
            userErrors { field message }
        }
    }
'''

MUTATION_COLLECTION_ADD_PRODUCTS = '''
    mutation collectionAddProducts($id: ID!, $productIds: [ID!]!) {
        collectionAddProducts(id: $id, productIds: $productIds) {
            collection { id title productsCount { count } }
            userErrors { field message }
        }
    }
'''

MUTATION_COLLECTION_REMOVE_PRODUCTS = '''
    mutation collectionRemoveProducts($id: ID!, $productIds: [ID!]!) {
        collectionRemoveProducts(id: $id, productIds: $productIds) {
            job { id done }
            userErrors { field message }
        }
    }
'''

# Shopify smart collection rule columns
_RULE_COLUMN_SELECTION = [
    ('TITLE',              'Product Title'),
    ('TYPE',               'Product Type'),
    ('VENDOR',             'Vendor'),
    ('VARIANT_PRICE',      'Price'),
    ('TAG',                'Tag'),
    ('VARIANT_INVENTORY',  'Inventory Stock'),
    ('VARIANT_WEIGHT',     'Weight'),
    ('VARIANT_COMPARE_AT_PRICE', 'Compare At Price'),
]

_RULE_RELATION_SELECTION = [
    ('EQUALS',       'is equal to'),
    ('NOT_EQUALS',   'is not equal to'),
    ('GREATER_THAN', 'is greater than'),
    ('LESS_THAN',    'is less than'),
    ('STARTS_WITH',  'starts with'),
    ('ENDS_WITH',    'ends with'),
    ('CONTAINS',     'contains'),
    ('NOT_CONTAINS', 'does not contain'),
]


class ShopifyCollection(models.Model):
    _name = 'shopify.collection'
    _description = 'Shopify Collection'
    _inherit = ['mail.thread']
    _order = 'name'

    name = fields.Char(string='Title', required=True)
    instance_id = fields.Many2one(
        'shopify.instance', string='Instance', required=True, ondelete='cascade',
    )

    # Shopify identity
    shopify_collection_id  = fields.Char(string='Collection ID', readonly=True)
    shopify_collection_gid = fields.Char(string='Collection GID', readonly=True)
    handle = fields.Char(
        string='Handle',
        help='URL-friendly identifier (e.g. "summer-sale"). Auto-generated by Shopify.',
        readonly=True,
    )

    # Type
    collection_type = fields.Selection([
        ('custom', 'Custom — manually curated'),
        ('smart',  'Smart — rule-based'),
    ], string='Type', default='custom', required=True)

    description = fields.Html(string='Description')
    image_url = fields.Char(string='Image URL', readonly=True)
    products_count = fields.Integer(string='Product Count', readonly=True)
    updated_at = fields.Datetime(string='Updated on Shopify', readonly=True)

    # Smart collection rules
    apply_disjunctively = fields.Boolean(
        string='Match ANY rule (OR)',
        help='Checked: product must match ANY rule. Unchecked: must match ALL rules (AND).',
        default=False,
    )
    rule_ids = fields.One2many('shopify.collection.rule', 'collection_id', string='Rules')

    # Product membership (custom collections)
    shopify_product_ids = fields.Many2many(
        'shopify.product',
        'shopify_collection_product_rel',
        'collection_id', 'product_id',
        string='Products',
        domain="[('instance_id', '=', instance_id)]",
    )

    sync_status = fields.Selection([
        ('draft',  'Not Synced'),
        ('synced', 'Synced'),
        ('error',  'Error'),
    ], default='draft', tracking=True)

    _unique_collection_per_instance = models.Constraint(
        'UNIQUE(instance_id, shopify_collection_id)',
        'This collection ID already exists for this instance.',
    )

    # ------------------------------------------------------------------
    # Import: Shopify → Odoo
    # ------------------------------------------------------------------

    @api.model
    def import_from_shopify(self, instance):
        cursor = None
        imported = 0
        while True:
            count, cursor, has_next = self.import_collections_page(instance, cursor)
            imported += count
            if not has_next:
                break
        _logger.info('Imported %d collections from %s', imported, instance.name)
        return imported

    def import_collections_page(self, instance, cursor=None):
        """Import one page of collections → (count, next_cursor, has_next).
        Used by the chunked background importer so each job stays small."""
        variables = {'first': 50, 'after': cursor}
        data = instance._graphql_request(QUERY_COLLECTIONS, variables=variables)
        connection = data.get('collections', {})
        edges = connection.get('edges', [])
        for edge in edges:
            self._upsert_collection(instance, edge['node'])
        page_info = connection.get('pageInfo', {})
        return len(edges), page_info.get('endCursor'), page_info.get('hasNextPage', False)

    def _upsert_collection(self, instance, node):
        gid = node['id']
        numeric_id = instance._gid_to_id(gid)
        existing = self.search([
            ('instance_id', '=', instance.id),
            ('shopify_collection_id', '=', numeric_id),
        ], limit=1)

        rule_set = node.get('ruleSet') or {}
        is_smart = bool(rule_set.get('rules'))
        updated = (node.get('updatedAt') or '').replace('T', ' ').replace('Z', '')

        vals = {
            'name':                    node.get('title', ''),
            'shopify_collection_id':   numeric_id,
            'shopify_collection_gid':  gid,
            'instance_id':             instance.id,
            'handle':                  node.get('handle', ''),
            'description':             node.get('descriptionHtml', ''),
            'collection_type':         'smart' if is_smart else 'custom',
            'apply_disjunctively':     rule_set.get('appliedDisjunctively', False),
            'products_count':          (node.get('productsCount') or {}).get('count', 0),
            'image_url':               (node.get('image') or {}).get('url', ''),
            'updated_at':              updated or False,
            'sync_status':             'synced',
        }

        if existing:
            existing.write(vals)
            col = existing
        else:
            col = self.create(vals)

        if is_smart:
            col.rule_ids.unlink()
            for rule in rule_set.get('rules', []):
                self.env['shopify.collection.rule'].create({
                    'collection_id': col.id,
                    'column':        rule.get('column', 'TITLE'),
                    'relation':      rule.get('relation', 'EQUALS'),
                    'condition':     rule.get('condition', ''),
                })

        return col

    # ------------------------------------------------------------------
    # Create on Shopify
    # ------------------------------------------------------------------

    def _build_collection_input(self):
        self.ensure_one()
        inp = {
            'title': self.name,
            'descriptionHtml': self.description or '',
        }
        if self.shopify_collection_gid:
            inp['id'] = self.shopify_collection_gid

        if self.collection_type == 'smart' and self.rule_ids:
            inp['ruleSet'] = {
                'appliedDisjunctively': self.apply_disjunctively,
                'rules': [
                    {'column': r.column, 'relation': r.relation, 'condition': r.condition}
                    for r in self.rule_ids
                ],
            }
        return inp

    def action_push_to_shopify(self):
        """Create or update this collection on Shopify."""
        for rec in self:
            inp = rec._build_collection_input()
            try:
                if rec.shopify_collection_gid:
                    data = rec.instance_id._graphql_request(
                        MUTATION_COLLECTION_UPDATE, variables={'input': inp}
                    )
                    result_key = 'collectionUpdate'
                else:
                    data = rec.instance_id._graphql_request(
                        MUTATION_COLLECTION_CREATE, variables={'input': inp}
                    )
                    result_key = 'collectionCreate'

                result = data.get(result_key, {})
                errors = result.get('userErrors', [])
                if errors:
                    raise UserError(_('Shopify error: %s') % errors[0]['message'])

                col_node = result.get('collection', {})
                gid = col_node.get('id', '')
                rec.write({
                    'shopify_collection_gid': gid,
                    'shopify_collection_id': rec.instance_id._gid_to_id(gid),
                    'handle': col_node.get('handle', rec.handle or ''),
                    'sync_status': 'synced',
                })
                _logger.info('Pushed collection "%s" to Shopify', rec.name)
            except UserError as e:
                rec.write({'sync_status': 'error'})
                raise

    def action_delete_from_shopify(self):
        """Delete this collection from Shopify and the local record."""
        self.ensure_one()
        if not self.shopify_collection_gid:
            self.unlink()
            return
        data = self.instance_id._graphql_request(
            MUTATION_COLLECTION_DELETE,
            variables={'input': {'id': self.shopify_collection_gid}},
        )
        errors = data.get('collectionDelete', {}).get('userErrors', [])
        if errors:
            raise UserError(_('Delete error: %s') % errors[0]['message'])
        self.unlink()

    # ------------------------------------------------------------------
    # Product membership (custom collections)
    # ------------------------------------------------------------------

    def action_sync_products_to_shopify(self):
        """Push current `shopify_product_ids` to this collection on Shopify."""
        self.ensure_one()
        if not self.shopify_collection_gid:
            raise UserError(_('Push the collection to Shopify first.'))
        if self.collection_type == 'smart':
            raise UserError(_('Smart collections manage products via rules — no manual add/remove.'))

        product_gids = [p.shopify_gid for p in self.shopify_product_ids if p.shopify_gid]
        if not product_gids:
            return

        data = self.instance_id._graphql_request(
            MUTATION_COLLECTION_ADD_PRODUCTS,
            variables={'id': self.shopify_collection_gid, 'productIds': product_gids},
        )
        errors = data.get('collectionAddProducts', {}).get('userErrors', [])
        if errors:
            raise UserError(_('Add products error: %s') % errors[0]['message'])

        count = data.get('collectionAddProducts', {}).get('collection', {}).get('productsCount', {}).get('count', 0)
        self.products_count = count
        return {
            'type': 'ir.actions.client',
            'tag': 'display_notification',
            'params': {
                'title': _('Products Synced'),
                'message': _('%d products now in "%s".') % (count, self.name),
                'type': 'success',
            },
        }

    def action_remove_products_from_shopify(self):
        """Remove all locally listed products from this collection on Shopify."""
        self.ensure_one()
        if not self.shopify_collection_gid:
            return
        product_gids = [p.shopify_gid for p in self.shopify_product_ids if p.shopify_gid]
        if not product_gids:
            return
        data = self.instance_id._graphql_request(
            MUTATION_COLLECTION_REMOVE_PRODUCTS,
            variables={'id': self.shopify_collection_gid, 'productIds': product_gids},
        )
        errors = data.get('collectionRemoveProducts', {}).get('userErrors', [])
        if errors:
            raise UserError(_('Remove products error: %s') % errors[0]['message'])

    # ------------------------------------------------------------------
    # Cron
    # ------------------------------------------------------------------

    @api.model
    def cron_sync_collections(self):
        instances = self.env['shopify.instance'].search([('state', '=', 'connected')])
        for instance in instances:
            try:
                self.import_from_shopify(instance)
            except Exception as e:
                _logger.error('Collection sync cron failed for %s: %s', instance.name, e)


class ShopifyCollectionRule(models.Model):
    """A single rule in a Shopify smart collection rule set."""
    _name = 'shopify.collection.rule'
    _description = 'Shopify Collection Rule'
    _order = 'collection_id, id'

    collection_id = fields.Many2one(
        'shopify.collection', string='Collection',
        required=True, ondelete='cascade',
    )
    column    = fields.Selection(_RULE_COLUMN_SELECTION,    string='Field',    required=True, default='TITLE')
    relation  = fields.Selection(_RULE_RELATION_SELECTION,  string='Condition', required=True, default='EQUALS')
    condition = fields.Char(string='Value', required=True)

    @api.depends('column', 'relation', 'condition')
    def _compute_display_name(self):
        col_labels = dict(_RULE_COLUMN_SELECTION)
        rel_labels = dict(_RULE_RELATION_SELECTION)
        for rec in self:
            rec.display_name = (
                f'{col_labels.get(rec.column, rec.column)} '
                f'{rel_labels.get(rec.relation, rec.relation)} "{rec.condition}"'
            )
